
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceSoap {


    /**
     * 接口相关信息
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetReleaseID", action = "http://tempuri.org/GetReleaseID")
    @WebResult(name = "GetReleaseIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReleaseID", targetNamespace = "http://tempuri.org/", className = "mypackage.GetReleaseID")
    @ResponseWrapper(localName = "GetReleaseIDResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.GetReleaseIDResponse")
    public String getReleaseID();

    /**
     * test
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/test")
    @WebResult(name = "testResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "test", targetNamespace = "http://tempuri.org/", className = "mypackage.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.TestResponse")
    public String test(
        @WebParam(name = "srtXml", targetNamespace = "http://tempuri.org/")
        String srtXml);

    /**
     * 将街镇派遣反馈信息发送到区(用于区级平台派遣街镇的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendOrderInfo", action = "http://tempuri.org/SendOrderInfo")
    @WebResult(name = "SendOrderInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendOrderInfo", targetNamespace = "http://tempuri.org/", className = "mypackage.SendOrderInfo")
    @ResponseWrapper(localName = "SendOrderInfoResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.SendOrderInfoResponse")
    public String sendOrderInfo(
        @WebParam(name = "srtXml", targetNamespace = "http://tempuri.org/")
        String srtXml);

    /**
     * 将街镇申请退单信息发送到区(用于区级平台派遣街镇的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendApplyDeptBack", action = "http://tempuri.org/SendApplyDeptBack")
    @WebResult(name = "SendApplyDeptBackResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendApplyDeptBack", targetNamespace = "http://tempuri.org/", className = "mypackage.SendApplyDeptBack")
    @ResponseWrapper(localName = "SendApplyDeptBackResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.SendApplyDeptBackResponse")
    public String sendApplyDeptBack(
        @WebParam(name = "srtXml", targetNamespace = "http://tempuri.org/")
        String srtXml);

    /**
     * 将街镇处理完成信息发送到区(用于区级平台派遣街镇的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSuperviseInfo", action = "http://tempuri.org/SendSuperviseInfo")
    @WebResult(name = "SendSuperviseInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSuperviseInfo", targetNamespace = "http://tempuri.org/", className = "mypackage.SendSuperviseInfo")
    @ResponseWrapper(localName = "SendSuperviseInfoResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.SendSuperviseInfoResponse")
    public String sendSuperviseInfo(
        @WebParam(name = "srtXml", targetNamespace = "http://tempuri.org/")
        String srtXml);

    /**
     * 将街镇延期申请信息发送到区(用于区级平台派遣街镇的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSolvingPostPoneMent", action = "http://tempuri.org/SendSolvingPostPoneMent")
    @WebResult(name = "SendSolvingPostPoneMentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSolvingPostPoneMent", targetNamespace = "http://tempuri.org/", className = "mypackage.SendSolvingPostPoneMent")
    @ResponseWrapper(localName = "SendSolvingPostPoneMentResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.SendSolvingPostPoneMentResponse")
    public String sendSolvingPostPoneMent(
        @WebParam(name = "srtXml", targetNamespace = "http://tempuri.org/")
        String srtXml);

    /**
     * 将街镇案件上报至区(用于街镇上报区的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendInputInfo", action = "http://tempuri.org/SendInputInfo")
    @WebResult(name = "SendInputInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendInputInfo", targetNamespace = "http://tempuri.org/", className = "mypackage.SendInputInfo")
    @ResponseWrapper(localName = "SendInputInfoResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.SendInputInfoResponse")
    public String sendInputInfo(
        @WebParam(name = "srtXml", targetNamespace = "http://tempuri.org/")
        String srtXml);

    /**
     * 将街镇登记受理信息同步至区(用于街镇自行流转的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPerCreateInfo", action = "http://tempuri.org/SendPerCreateInfo")
    @WebResult(name = "SendPerCreateInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPerCreateInfo", targetNamespace = "http://tempuri.org/", className = "mypackage.SendPerCreateInfo")
    @ResponseWrapper(localName = "SendPerCreateInfoResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.SendPerCreateInfoResponse")
    public String sendPerCreateInfo(
        @WebParam(name = "srtXml", targetNamespace = "http://tempuri.org/")
        String srtXml);

    /**
     * 将街镇派遣和返工信息同步至区(用于街镇自行流转的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendDispatchInfo", action = "http://tempuri.org/SendDispatchInfo")
    @WebResult(name = "SendDispatchInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendDispatchInfo", targetNamespace = "http://tempuri.org/", className = "mypackage.SendDispatchInfo")
    @ResponseWrapper(localName = "SendDispatchInfoResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.SendDispatchInfoResponse")
    public String sendDispatchInfo(
        @WebParam(name = "srtXml", targetNamespace = "http://tempuri.org/")
        String srtXml);

    /**
     * 将街镇处置信息同步至区(用于街镇自行流转的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSolvingInfo", action = "http://tempuri.org/SendSolvingInfo")
    @WebResult(name = "SendSolvingInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSolvingInfo", targetNamespace = "http://tempuri.org/", className = "mypackage.SendSolvingInfo")
    @ResponseWrapper(localName = "SendSolvingInfoResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.SendSolvingInfoResponse")
    public String sendSolvingInfo(
        @WebParam(name = "srtXml", targetNamespace = "http://tempuri.org/")
        String srtXml);

    /**
     * 将街镇结案信息同步至区(用于街镇自行流转的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendEndInfo", action = "http://tempuri.org/SendEndInfo")
    @WebResult(name = "SendEndInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendEndInfo", targetNamespace = "http://tempuri.org/", className = "mypackage.SendEndInfo")
    @ResponseWrapper(localName = "SendEndInfoResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.SendEndInfoResponse")
    public String sendEndInfo(
        @WebParam(name = "srtXml", targetNamespace = "http://tempuri.org/")
        String srtXml);

    /**
     * 将街镇作废信息同步至区(用于街镇自行流转的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCancelInfo", action = "http://tempuri.org/SendCancelInfo")
    @WebResult(name = "SendCancelInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCancelInfo", targetNamespace = "http://tempuri.org/", className = "mypackage.SendCancelInfo")
    @ResponseWrapper(localName = "SendCancelInfoResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.SendCancelInfoResponse")
    public String sendCancelInfo(
        @WebParam(name = "srtXml", targetNamespace = "http://tempuri.org/")
        String srtXml);

    /**
     * 区平台数据字典
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCodeList", action = "http://tempuri.org/GetCodeList")
    @WebResult(name = "GetCodeListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCodeList", targetNamespace = "http://tempuri.org/", className = "mypackage.GetCodeList")
    @ResponseWrapper(localName = "GetCodeListResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.GetCodeListResponse")
    public String getCodeList();

    /**
     * 将市水务案件上报到区中心
     * 
     * @param info
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getInfo")
    @WebResult(name = "getInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getInfo", targetNamespace = "http://tempuri.org/", className = "mypackage.GetInfo")
    @ResponseWrapper(localName = "getInfoResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.GetInfoResponse")
    public String getInfo(
        @WebParam(name = "info", targetNamespace = "http://tempuri.org/")
        String info);

    /**
     * 将市水务案件延期审核反馈入库
     * 
     * @param info
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getYQSHInfo")
    @WebResult(name = "getYQSHInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getYQSHInfo", targetNamespace = "http://tempuri.org/", className = "mypackage.GetYQSHInfo")
    @ResponseWrapper(localName = "getYQSHInfoResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.GetYQSHInfoResponse")
    public String getYQSHInfo(
        @WebParam(name = "info", targetNamespace = "http://tempuri.org/")
        String info);

    /**
     * 将市水务案件退单审核反馈入库
     * 
     * @param info
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getBackInfo")
    @WebResult(name = "getBackInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getBackInfo", targetNamespace = "http://tempuri.org/", className = "mypackage.GetBackInfo")
    @ResponseWrapper(localName = "getBackInfoResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.GetBackInfoResponse")
    public String getBackInfo(
        @WebParam(name = "info", targetNamespace = "http://tempuri.org/")
        String info);

}
