
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceHttpPost", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceHttpPost {


    /**
     * 接口相关信息
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetReleaseID")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getReleaseID();

    /**
     * test
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String test(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "srtXml")
        String srtXml);

    /**
     * 将街镇派遣反馈信息发送到区(用于区级平台派遣街镇的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendOrderInfo")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String sendOrderInfo(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "srtXml")
        String srtXml);

    /**
     * 将街镇申请退单信息发送到区(用于区级平台派遣街镇的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendApplyDeptBack")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String sendApplyDeptBack(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "srtXml")
        String srtXml);

    /**
     * 将街镇处理完成信息发送到区(用于区级平台派遣街镇的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSuperviseInfo")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String sendSuperviseInfo(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "srtXml")
        String srtXml);

    /**
     * 将街镇延期申请信息发送到区(用于区级平台派遣街镇的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSolvingPostPoneMent")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String sendSolvingPostPoneMent(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "srtXml")
        String srtXml);

    /**
     * 将街镇案件上报至区(用于街镇上报区的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendInputInfo")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String sendInputInfo(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "srtXml")
        String srtXml);

    /**
     * 将街镇登记受理信息同步至区(用于街镇自行流转的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPerCreateInfo")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String sendPerCreateInfo(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "srtXml")
        String srtXml);

    /**
     * 将街镇派遣和返工信息同步至区(用于街镇自行流转的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendDispatchInfo")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String sendDispatchInfo(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "srtXml")
        String srtXml);

    /**
     * 将街镇处置信息同步至区(用于街镇自行流转的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSolvingInfo")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String sendSolvingInfo(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "srtXml")
        String srtXml);

    /**
     * 将街镇结案信息同步至区(用于街镇自行流转的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendEndInfo")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String sendEndInfo(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "srtXml")
        String srtXml);

    /**
     * 将街镇作废信息同步至区(用于街镇自行流转的案件)
     * 
     * @param srtXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCancelInfo")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String sendCancelInfo(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "srtXml")
        String srtXml);

    /**
     * 区平台数据字典
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCodeList")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getCodeList();

    /**
     * 将市水务案件上报到区中心
     * 
     * @param info
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getInfo(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "info")
        String info);

    /**
     * 将市水务案件延期审核反馈入库
     * 
     * @param info
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getYQSHInfo(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "info")
        String info);

    /**
     * 将市水务案件退单审核反馈入库
     * 
     * @param info
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getBackInfo(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "info")
        String info);

}
